<script type="text/javascript" src="tools/angular.min.js"></script>
<script type="text/javascript" src="tools/jquery.js"></script>
<script type="text/javascript" src="tools/underscore-min.js"></script>
<script type="text/javascript" src="tools/tooltipster.min.js"></script>
<script type="text/javascript" src="tools/bootstrap.min.js"></script>
<script type="text/javascript" src="tools/date-en-AU.js"></script>
<script type="text/javascript" src="tools/time.js"></script>
<script type="text/javascript" src="tools/moment.js"></script>
{{--<script type="text/javascript" src="tools/mousetrap.min.js"></script>--}}
<script type="text/javascript" src="tools/checklist-model.js"></script>
<script type="text/javascript" src="tools/angular-animate.min.js"></script>